version: '3.7'

services:

  localstack:
    container_name: localstack_container
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3
    volumes:
      - "localstack_data:/tmp/localstack"
      - "./scripts:/etc/localstack/init/ready.d"

volumes:
  localstack_data: